### ISSUE TITLE
Getting errors with the add-on

### ISSUE THREAD

**Issue by wushugirl05** [TruongQToan/Automatically-flip-cards#7]
Here is one of the errors I get with the addon

`
Traceback (most recent call last):
  File "aqt/progress.pyc", line 69, in handler
  File "/Users/Jessica/Library/Application Support/Anki2/addons/Automatically_flip_cards.py", line 213, in change_card
    mw.reviewer._answerCard(mw.reviewer._defaultEase())
  File "aqt/reviewer.pyc", line 271, in _answerCard
  File "aqt/reviewer.pyc", line 105, in nextCard
  File "aqt/reviewer.pyc", line 221, in _showQuestion
  File "anki/hooks.pyc", line 26, in runHook
  File "/Users/Jessica/Library/Application Support/Anki2/addons/Automatically_flip_cards.py", line 227, in show_question
    set_time_limit()
  File "/Users/Jessica/Library/Application Support/Anki2/addons/Automatically_flip_cards.py", line 191, in set_time_limit
    audio_fields_q, audio_fields_a = split_audio_fields(card, model, audio_fields)
  File "/Users/Jessica/Library/Application Support/Anki2/addons/Automatically_flip_cards.py", line 119, in split_audio_fields
    t = m['tmpls'][card.ord]
IndexError: list index out of range`

**Comment by TruongQToan** [comment]
Could you share me the deck that produces this error?

**Comment by Z1839** [comment]
It also keeps crashing for me.

**Comment by toantruong95** [comment]
Could you share a screen of the issue?

**Comment by Z1839** [comment]
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.3
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-19 07:35:59
Add-ons possibly involved: ⁨Automatically flip cards⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 76, in handler
  File "/Users/O73190/Library/Application Support/Anki2/addons21/631932779/__init__.py", line 214, in change_card
    mw.reviewer._answerCard(mw.reviewer._defaultEase())
  File "aqt/reviewer.py", line 270, in _answerCard
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-54>", line 2, in nextCard
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 661, in repl
  File "aqt/reviewer.py", line 108, in nextCard
  File "aqt/reviewer.py", line 210, in _showQuestion
  File "aqt/gui_hooks.py", line 1409, in __call__
  File "anki/hooks.py", line 611, in runHook
  File "/Users/O73190/Library/Application Support/Anki2/addons21/631932779/__init__.py", line 228, in show_question
    set_time_limit()
  File "/Users/O73190/Library/Application Support/Anki2/addons21/631932779/__init__.py", line 190, in set_time_limit
    audio_fields_q, audio_fields_a = split_audio_fields(card, model, audio_fields)
  File "/Users/O73190/Library/Application Support/Anki2/addons21/631932779/__init__.py", line 118, in split_audio_fields
    t = m['tmpls'][card.ord]
IndexError: list index out of range



Here is the error message. I appreciate the updates. This app is going to be a game changer for me!

**Comment by TruongQToan** [comment]
I have updated the add on. You can update it and report me if you still get the issue.

**Comment by Z1839** [comment]
Seems to be working fine for now. I was wondering if you could clarify the "add additional time to X" options. Do they literally add on extra seconds to the default time? It would be easier to allow to type the times in for front and back, rather than "adding" time.

**Comment by toantruong95** [comment]
The time is added to the default time. The default time is based on the audio time of the front or back. I have chosen that based on my need. You can choose `Change default waiting time` in the menu to change the default waiting time.
