### ISSUE TITLE
"import decimal fails" on startup

### ISSUE THREAD

**Issue by Max-Hasin** [TruongQToan/Automatically-flip-cards#9]
Hi, on first installation I get this error: 

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.
When loading 'Automatically flip cards':
Traceback (most recent call last):
  File "aqt/addons.py", line 80, in loadAddons
  File "/home/lig/.local/share/Anki2/addons21/631932779/__init__.py", line 9, in <module>
    from .mutagen.mp3 import MP3
  File "/home/lig/.local/share/Anki2/addons21/631932779/mutagen/__init__.py", line 22, in <module>
    from ._util import MutagenError
  File "/home/lig/.local/share/Anki2/addons21/631932779/mutagen/_util.py", line 19, in <module>
    import decimal
ModuleNotFoundError: No module named 'decimal' 

This happens on Lubuntu 19.04, have not yet tried in on a Windows machine. 

Thanks

**Comment by TruongQToan** [comment]
Have you updated the addon to the latest?
